name: Build Docker Image and Push to Gitea Registry

on:
  push:
    tags:
      - 'v*'

env:
  GITEA_USERNAME: ${{ secrets.USERNAME }}
  GITEA_TOKEN: ${{ secrets.TOKEN }}
  GITEA_HOST: ${{ vars.HOST }}
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  docker_build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Gitea Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GITEA_HOST }}
          username: ${{ env.GITEA_USERNAME }}
          password: ${{ env.GITEA_TOKEN }}

      - name: Build Docker Image
        run: |
          echo "Tag name from github.ref_name: ${IMAGE_TAG#v}"
          docker build -t "$GITEA_HOST/$IMAGE_NAME:${IMAGE_TAG#v}" .
          docker tag "$GITEA_HOST/$IMAGE_NAME:${IMAGE_TAG#v}" "$GITEA_HOST/$IMAGE_NAME:latest"

      - name: Push Docker Image to Gitea Registry
        run: |
          docker push "$GITEA_HOST/$IMAGE_NAME:${IMAGE_TAG#v}"
          docker push "$GITEA_HOST/$IMAGE_NAME:latest"
